class SamsungKeys:
    keys = [
        {"code": "KEY_HOME", "label": "Home"},
        {"code": "KEY_POWER", "label": "Power off"},
        {"code": "KEY_UP", "label": "Up"},
        {"code": "KEY_DOWN", "label": "Down"},
        {"code": "KEY_LEFT", "label": "Left"},
        {"code": "KEY_RIGHT", "label": "Right"},
        {"code": "KEY_CHUP", "label": "P+"},
        {"code": "KEY_CHDOWN", "label": "P-"},
        {"code": "KEY_ENTER", "label": "OK"},
        {"code": "KEY_RETURN", "label": "Return"},
        {"code": "KEY_EXIT", "label": "Exit"},
        {"code": "KEY_CONTENTS", "label": "Smart Hub"},
        {"code": "KEY_CH_LIST", "label": "Channel List"},
        {"code": "KEY_MENU", "label": "Menu"},
        {"code": "KEY_SOURCE", "label": "Source"},
        {"code": "KEY_GUIDE", "label": "Guide"},
        {"code": "KEY_TOOLS", "label": "Tools"},
        {"code": "KEY_INFO", "label": "Info"},
        {"code": "KEY_RED", "label": "Red"},
        {"code": "KEY_GREEN", "label": "Green"},
        {"code": "KEY_YELLOW", "label": "Yellow"},
        {"code": "KEY_BLUE", "label": "Blue"},
        {"code": "KEY_PANNEL_CHDOWN", "label": "3D"},
        {"code": "KEY_VOLUP", "label": "Volume Up"},
        {"code": "KEY_VOLDOWN", "label": "Volume Down"},
        {"code": "KEY_MUTE", "label": "Mute"},
        {"code": "KEY_SUB_TITLE", "label": "Sub title"},
        {"code": "KEY_SOUND_MODE", "label": "Sound mode"},
        {"code": "KEY_0", "label": "0"},
        {"code": "KEY_1", "label": "1"},
        {"code": "KEY_2", "label": "2"},
        {"code": "KEY_3", "label": "3"},
        {"code": "KEY_4", "label": "4"},
        {"code": "KEY_5", "label": "5"},
        {"code": "KEY_6", "label": "6"},
        {"code": "KEY_7", "label": "7"},
        {"code": "KEY_8", "label": "8"},
        {"code": "KEY_9", "label": "9"},
        {"code": "KEY_HDMI", "label": "HDMI"},
        {"code": "KEY_REC", "label": "Record"},
        {"code": "KEY_PAUSE", "label": "Pause"},
        {"code": "KEY_PLAY", "label": "Play"},
        {"code": "KEY_STOP", "label": "Stop"},
        {"code": "KEY_FF", "label": "Fast forward"},
        {"code": "KEY_REWIND", "label": "Rewind"},
        {"code": "KEY_PRECH", "label": "Pre-Channel"},
    ]
